version: '3.9'
services:
  my_django_app:
    build: 
      context: ./django_folder
    image: my_django_app:1.0
    ports:
      - 8000:8000
    container_name: django_container
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=mysql_container
      - DB_NAME=${DATABASE}
      - DB_USER=${USER}
      - DB_PASS=${PASSW}
      - DEBUG=1
    depends_on:
      mysql_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql_db:
    image: mysql:8.4
    container_name: mysql_container
    environment:
      MYSQL_ROOT_USER: ${USER}
      MYSQL_ROOT_PASSWORD: ${PASSW}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  data:
    