version: '3.9'
services:
  my_django_app:
    build: 
      context: ./django_folder
    image: my_django_app:1.0
    volumes:
      - static_files:/django_folder/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    container_name: django_container
    command: >
      sh -c "python manage.py migrate && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=mysql_container
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DEBUG=1
      - CSRF_TRUSTED=${CSRF_TRUSTED}
    depends_on:
      mysql_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 300s
      timeout: 5s
      retries: 3

  mysql_db:
    image: mysql:8.4
    container_name: mysql_container
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3

  django_nginx:
    build: 
      context: ./nginx
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - static_files:/home/myapp/staticfiles
    depends_on:
      - my_django_app

volumes:
  data:
  static_files:
    