version: '3.9'
services:
  my_django_app:
    build: 
      context: ./django_folder
    image: my_django_app:1.0
    ports:
      - 8000:8000
    container_name: django_container
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    